### ISSUE TITLE
DevPost MVP Description

### ISSUE THREAD

**Issue by ShabazBadshah** [grey-software/open-local-governance#20]
# Problem Statement

The current payment collection system within Pakistan for municipal Government Services is one that easily exploited. Illegitimate parties can siphon additional monetary resources from citizens for personal incentives. The municipal Government requires a solution that can mitigate the misuse of financial resources and provide transparency to the municipal Government in regards to where their citizens' financial resources are flowing.

# Our Solution

Our solution mitigates the requirement for a third-party in the fee collection pipeline while providing an immutable audit trail to track and reduce illegitimate financial transactions with the Government for their services. We allow the municipal Government to collect service charges from citizens such as tolls, garbage collection fees, and utility bills ensuring financial data security. Citizens are provided with a simple, accessible, and secure method of payment through integration with Telenor Easypaisa. Furthermore, the data obtained from citizens can allow Government staff to inform their future financial decisions.

# Key Features

- App can receive payment notifications from the government.
- App can receive payments from various popular payment processors.
- App can track citizen via government ID.
- Alerts for overdue fees can be easily seen and paid by citizens.

# Roadmap

Future goals for the project include leveraging modern technologies to better facilitate the function of the Government. The current feature-set is based on the existing requirements of the municipal Government, and will require consistent discussion and research to expand onto. Some functionality that we will add in the future is as follows:

## Citizen App
- Urdu localization support
- In-app tutorial for first-time users
- Dark mode for saving battery life
- 1-click contact for government support
- View payment history
- Export all personal data offline
- Switching between Urdu and English languages
- Feedback form
- Deferring payments

## Government Dashboard
- Download report of all transactions for a citizen
- Add additional government services to be paid for
- SQL-like data aggregation and search
- User generated reports
- Detailed audit logging
- User roles and permissions
- Search for citizens
- Interactive jurisdiction browser map
- Support staging, testing, and production environments for new service rollouts

# Links
[Github Source Code Repository](https://github.com/grey-software/hackathon-2020-codeforpak-civictech/)
**MVP Demo Site**

**Comment by ShabazBadshah** [comment]
# Problem Statement

# Our Solution

# Key Features

# Links
**Github Repository**
**MVP Demo Site**

**Comment by ayu2234** [comment]
# Problem Statement

The current payment collection system within Pakistan for Government Services is one that is liable to exploitation by parties in the pipeline between the citizen and government. 

Our solution mitigates the need for middlemen parties in the fee collection pipeline while providing an immutable audit trail to track and reduce illegitimate transactions.

Future goals for the project include leveraging modern technologies to better facilitate the function of the government.

# Our Solution

Our solution begins with our strategy, which is to leverage modern technologies to reform the government's fee collection pipeline.

Our goals for the solution is then to:

#### 1) Stop the loss of wealth due to 'leakages' 

#### 2) Introduce citizens to a method to pay the government that is:
- Simple
- Accessible
- Fast
- Secure

#### 3) Introduce government staff to modern methods and tools

To achieve these goals, our solution will:

### 1) 
Mitigate the need for middlemen in the fee collection pipeline while providing an immutable audit trail to track and reduce illegitimate transactions.

### 2) 
Allow citizens to directly pay the government through a mobile application that leverages Pakistan's major phone-banking solutions. 

### 3) 
Introduce a dashboard that allows government staff to monitor payment statistics at a glance.

# Key Features

# Links
**Github Repository**
**MVP Demo Site**

**Comment by ayu2234** [comment]
# Problem Statement

The current payment collection system within Pakistan for municipal Government Services is one that easily exploited. Illegitimate parties are currently known to exploit the current system to siphon wealth from citizens for their personal incentives. The municipal government requires a solution that can mitigate the misuse of financial resources and provide transparency to the municipal government in regards to where their citizens' financial resources are flowing.

# Our Solution

Three goals were identified for the solution:

#### 1) Stop the loss of wealth due to 'leakages' 

#### 2) Introduce citizens to a method to pay the government that is:
- Simple
- Accessible
- Fast
- Secure

#### 3) Introduce government staff to modern methods and tools

Our solution mitigates the requirement for a third-party in the fee collection pipeline while providing an immutable audit trail to track and eliminate illegitimate financial transactions with the Government for their services. We allow the municipal government to collect service charges from citizens such as tolls, garbage collection fees, and utility bills ensuring financial data security. Citizens are provided with a simple, accessible, and secure method of payment through integration with Telenor Easypaisa. Furthermore, the data obtained from citizens can allow Government staff to inform their future financial decisions.

# Key Features

# Roadmap

## Citizen App
- Urdu localization support
- In-app tutorial for first-time users
- Dark mode for saving battery life
- 1-click contact for government support
- View personal payment history
- Export all personal data offline
- Switching between Urdu and English languages
- Feedback form

## Government Dashboard
- Download report of all transactions for a citizen
- Add additional government services to be paid for
- SQL-like data aggregation and search
- User generated reports
- Detailed audit logging
- User roles and permissions
- Search for citizens
- Interactive jurisdiction browser map
- Support staging, testing, and production environments for new service rollouts

# Links
[Github Source Code Repository](https://github.com/grey-software/hackathon-2020-codeforpak-civictech/)
**MVP Demo Site**

**Comment by ShabazBadshah** [comment]
# Problem Statement

The current payment collection system within Pakistan for municipal Government Services is one that easily exploited. Illegitimate parties can siphon additional monetary resources from citizens for personal incentives. The municipal Government requires a solution that can mitigate the misuse of financial resources and provide transparency to the municipal Government in regards to where their citizens' financial resources are flowing.

# Our Solution

Our solution mitigates the requirement for a third-party in the fee collection pipeline while providing an immutable audit trail to track and reduce illegitimate financial transactions with the Government for their services. We allow the municipal Government to collect service charges from citizens such as tolls, garbage collection fees, and utility bills ensuring financial data security. Citizens are provided with a simple, accessible, and secure method of payment through integration with Telenor Easypaisa. Furthermore, the data obtained from citizens can allow Government staff to inform their future financial decisions.

# Key Features

- App can receive payment notifications from the government.
- App can receive payments from various popular payment processors.
- App can track citizen via government ID.
- Alerts for overdue fees can be easily seen and paid by citizens.

# Roadmap

Future goals for the project include leveraging modern technologies to better facilitate the function of the Government. The current feature-set is based on the existing requirements of the municipal Government, and will require consistent discussion and research to expand onto. Some functionality that we will add in the future is as follows:

## Citizen App
- Urdu localization support
- In-app tutorial for first-time users
- Dark mode for saving battery life
- 1-click contact for government support
- View payment history
- Export all personal data offline
- Switching between Urdu and English languages
- Feedback form
- Deferring payments

## Government Dashboard
- Download report of all transactions for a citizen
- Add additional government services to be paid for
- SQL-like data aggregation and search
- User generated reports
- Detailed audit logging
- User roles and permissions
- Search for citizens
- Interactive jurisdiction browser map
- Support staging, testing, and production environments for new service rollouts

# Links
[Github Source Code Repository](https://github.com/grey-software/hackathon-2020-codeforpak-civictech/)
**MVP Demo Site**

**Comment by ShabazBadshah** [comment]
See last comment for final MVP description submission. Closing issue as the CodeForPakistan Hackathon has now concluded
